# AUTOGENERATED! DO NOT EDIT! File to edit: ../01_basics.ipynb.

# %% auto 0
__all__ = []

# %% ../01_basics.ipynb 2
from fastai import *
from fastcore import *
from fastcore.foundation import *
from fastcore.utils import *
from fastcore.test import *
from nbdev.showdoc import *
from fastcore.nb_imports import *

# %% ../01_basics.ipynb 5
show_doc(ifnone)

# %% ../01_basics.ipynb 7
test_eq(ifnone(None, 1), 1)
test_eq(ifnone(2, 1), 2)
